### ISSUE TITLE
Self-hosted vs. Systemd

### ISSUE THREAD

**Issue by teemow** [kinvolk/kubeadm-systemd#1]
Hey @nhlfr! @blixtra pointed me here and I am wondering what the direction of this would be. We've done a lot of systemd/kubernetes in the past although we are slowly moving away from this. So I am happy to share some thoughts about this.

Obviously I don't know much about the scope of this tool so please ignore any false assumptions.

I'll try to list a few options to Integrate with systemd here:
1) generating the units to run a kubernetes on systemd. using either go binaries or rkt/runc to start container images with kubernetes binaries. using systemd-run to run those units right away.
2) using systemd-nspawn to start os images on a host that then use kubeadm to create a cluster
3) using systemd to start a kubelet and then start a self-hosted cluster rendered with something like bootkube. There is not much need to have something else than a kubelet if you go for the self-hosted kubernetes and that is what we do nowadays more or less.

You see I am just guessing and curious. Can you tell me more about your plans? And maybe we can help finding a good direction that is useful for the community.

Also pinging the kubeadm developers in case you haven't talked to them before @errordeveloper @lukemarsden @pires

**Comment by errordeveloper** [comment]
To me the main question is – what would be the outcome, e.g. are we looking to have a quick way for spinning up test clusters of size N locally (may be even nested) or something else?

**Comment by nhlfr** [comment]
Hey @teemow, the goal of this project is exactly what you described in option 2.

We are going to run N systemd-nspawn containers and then use kubeadm to create a kubernetes cluster. I would like to focus mostly on setting up kubernetes both from locally built source code, so this tool is addressed mostly for developers **of** kubernetes and is going to be an alternative for:
- vagrant provider - which is very problematic for developers, doesn't work well on all distros (for me personally, it doesn't work at all...)
- https://github.com/sttts/kubernetes-dind-cluster or https://github.com/Mirantis/kubeadm-dind-cluster - in my opinion, Docker isn't a very good tool for simulating a cluster node, since its an application container engine, not an operating system container engine (like systemd-nspawn or lxc); also, the second project isn't fully working ATM

We may try to give a possibility to set up stable versions of k8s (from packages) as well, but the use case for developers is IMO more important ATM.

@errordeveloper Yes, the main reason behind creating this project is that we would like to have a quick way to deploy a kubernetes cluster (from source) and minimize the difference between "deployment on production" and "deployment from code I modified on my laptop".
I'm not sure what do you mean by "nested clusters", for now we want to treat systemd-nspawn containers as nodes, and run Docker daemon inside them to be used by kubernetes.

I will to put the info above (maybe with some details I possibly forgot about) into README/wiki soon.

**Comment by teemow** [comment]
@nhlfr ack. sounds great! I've used docker in nspawn too and that worked very well for me. The old code is here: 

* https://github.com/teemow/conair
* https://github.com/teemow/conair-coreos

Do you want to keep this issue open as a reminder to add stuff to the readme? Feel free to close otherwise.
